name: ECR
description: Login to ECR in your build steps
author: https://github.com/lox
requirements:
  - curl
  - bash
  - aws
configuration:
  properties:
    login:
      type: boolean
    account-ids:
      type:
        - string
        - array
      minItems: 1
    no-include-email:
      type: boolean
    region:
      type: string
    assume-role:
      type: object
      properties:
        role-arn:
          type: string
        oidc:
          type: boolean
        duration-seconds:
          type: number
          default: 3600
    profile:
      type: string
  required:
    - login
