steps:
  - label: ":shell: Tests"
    plugins:
      - plugin-tester#v1.0.0: ~

  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.0.0:
          id: ecr

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.3.0:
          files: hooks/**
    skip: "Shellcheck doesn't pass right now"
