#!/bin/bash
set -eu -o pipefail

# Reads either a value or a list from plugin config
function plugin_read_list() {
  local prefix="BUILDKITE_PLUGIN_ECR_$1"
  local parameter="${prefix}_0"

  if [[ -n "${!parameter:-}" ]]; then
    local i=0
    local parameter="${prefix}_${i}"
    while [[ -n "${!parameter:-}" ]]; do
      echo "${!parameter}"
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  elif [[ -n "${!prefix:-}" ]]; then
    echo "${!prefix}"
  fi
}

# Retries a command on failure.
function retry() {
  local -r -i retries="$1"; shift
  local -i max_attempts=$((retries + 1))
  local -i attempt_num=1
  local exit_code

  until "$@" ; do
    exit_code=$?
    echo "$attempt_num == $retries" >&2
    if [[ $retries -eq 0 ]] ; then
      return $exit_code
    elif (( attempt_num == max_attempts )) ; then
      echo "Login failed after $attempt_num attempts" >&2
      return $exit_code
    else
      echo "Login failed on attempt ${attempt_num} of ${max_attempts}. Trying again in $attempt_num seconds..." >&2
      sleep $(( attempt_num++ ))
    fi
  done
}

function login() {
  echo "~~~ Authenticating with AWS ECR :ecr: :docker:"
  local region="${BUILDKITE_PLUGIN_ECR_REGISTRY_REGION:-${BUILDKITE_PLUGIN_ECR_REGION:-${AWS_DEFAULT_REGION:-}}}"
  if [[ -z $region ]]; then
    region="us-east-1"
    echo >&2 "AWS region should be specified via plugin config or AWS_DEFAULT_REGION environment."
    echo >&2 "Defaulting to $region for legacy compatibility."
  fi
  account_ids=()
  while IFS='' read -r line; do account_ids+=("$line"); done < <(plugin_read_list ACCOUNT_IDS | tr "," "\n")
  # check if account_ids is empty, or only contains an empty string.
  # just testing [[ -z ${account_ids[*]} ]] breaks on bash 3.x if the array is empty.
  if [[ ${#account_ids[@]} -eq 0 || -z "${account_ids[*]}" ]]; then
    account_ids=("$(aws sts get-caller-identity --query Account --output text)")
  fi
  if [[ ${#account_ids[@]} -eq 0 || -z "${account_ids[*]}" ]]; then
    echo >&2 "AWS account ID required via plugin config or 'aws sts get-caller-identity'"
    exit 1
  fi
  # amend the ~~~ log heading with ^^^ to add the AWS account IDs
  echo "^^^ Authenticating with AWS ECR in $region for ${account_ids[*]} :ecr: :docker:"
  local password; password="$(retry "${BUILDKITE_PLUGIN_ECR_RETRIES:-0}" aws --region "$region" ecr get-login-password)"
  for account_id in "${account_ids[@]}"; do
    docker login --username AWS --password-stdin "$account_id.dkr.ecr.$region.amazonaws.com" <<< "$password"
  done
}

# For logging into the current AWS account’s registry
if [[ "${BUILDKITE_PLUGIN_ECR_LOGIN:-}" =~ ^(true|1)$ ]] ; then
  login
fi
