#!/bin/bash

set -eu -o pipefail

# Reads either a value or a list from plugin config
function plugin_read_list() {
  local prefix="BUILDKITE_PLUGIN_ECR_$1"
  local parameter="${prefix}_0"

  if [[ -n "${!parameter:-}" ]]; then
    local i=0
    local parameter="${prefix}_${i}"
    while [[ -n "${!parameter:-}" ]]; do
      echo "${!parameter}"
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  elif [[ -n "${!prefix:-}" ]]; then
    echo "${!prefix}"
  fi
}

if [[ -z "${AWS_DEFAULT_REGION:-}" ]] ; then
  export AWS_DEFAULT_REGION=us-east-1
fi

# For logging into the current AWS account’s registry
if [[ "${BUILDKITE_PLUGIN_ECR_LOGIN:-}" =~ ^(true|1)$ ]] ; then
  registry_ids=( $(plugin_read_list ACCOUNT_IDS) )
  login_args=()

  if [[ ${#registry_ids[@]} -gt 0 ]] ; then
    login_args=("--registry-ids" "${registry_ids[@]}")
  fi

  echo "~~~ Authenticating with AWS ECR"
  if [[ ${#login_args[@]} -gt 0 ]] ; then
    if ! ecr_login=$(aws ecr get-login "${login_args[@]}") ; then
      echo echo "~~~ :warning: ECR login failed"
      exit 1
    fi
  else
    if ! ecr_login=$(aws ecr get-login) ; then
      echo echo "~~~ :warning: ECR login failed"
      exit 1
    fi
  fi

  eval "$ecr_login"
fi